name: plain_launcher
description: An Android launcher designed to be senior-friendly.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  husky: ^0.1.6

flutter:
  uses-material-design: true
  # assets:
    # - lib/assets/
