name: plain_launcher
description: An Android launcher designed to be senior-friendly.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  date_format: ^2.0.7
  device_apps: ^2.2.0
  flutter:
    sdk: flutter
  flutter_accessibility_service: ^0.2.2
  flutter_expanded_tile: ^0.3.7
  fluttercontactpicker: ^4.7.0
  image_picker: ^0.8.7+5
  path_provider: ^2.0.15
  provider: ^6.0.5
  reorderables: ^0.6.0
  shared_preferences: ^2.1.1
  wave: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  husky: ^0.1.6

flutter:
  uses-material-design: true
  # assets:
    # - lib/assets/
