name: plain_launcher
description: An Android launcher designed to be senior-friendly.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  date_format: ^2.0.7
  device_apps: ^2.2.0
  flex_color_picker: ^3.2.1
  flutter:
    sdk: flutter
  provider: ^6.0.5
  reorderables: ^0.6.0
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  husky: ^0.1.6

flutter:
  uses-material-design: true
  # assets:
    # - lib/assets/
